emailservice:
  validationLink : http://127.0.0.1:8080/activation/
  AdminEmailValidationLink : http://127.0.0.1:8080/admincheck/
  adminKeyEmailAddress : eugen.fazekas@gmail.com
  subjecten : Demo Project account activation
  text1en : Dear
  text2en : "Thanks for you're registration to our website, and you can sign is with the followed username: "
  text3en : You can activate you're account by the followed link
  
  subjecthu : Demo Project Fiók aktiválás
  text1hu : Kedves
  text2hu : "Köszönjuk hogy regisztráltal az oldalon, és a következő felhasználó nével tudsz bejelentkezni: "
  text3hu : A fiókodat a következő oldalról tudod aktiválni
  
  subjectro : Demo Project activare cont
  text1ro : Drag client
  text2ro : "Multumim ca ai registrat pe pagina, si cu urmatoaru nume utlizator poti loga pe site: "
  text3ro : Po-ti activa contul pe linkul urmator
  
