CREATE TABLE IF NOT EXISTS users (
id INT AUTO_INCREMENT PRIMARY KEY,
fullname VARCHAR(64) NOT NULL,
email VARCHAR(64) NOT NULL,
UNIQUE KEY UK_email (email),
password VARCHAR(64) NOT NULL,
activation VARCHAR(64) NOT NULL,
enabled VARCHAR(64) NOT NULL ,
authority VARCHAR(64) NOT NULL 
);

CREATE TABLE IF NOT EXISTS blogs (
id INT AUTO_INCREMENT PRIMARY KEY,
blogger  VARCHAR_IGNORECASE  NOT NULL,
title  VARCHAR_IGNORECASE  NOT NULL,
content  CLOB NOT NULL,
posted TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS stories (
id INT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(128) NOT NULL,
content1 CLOB ,
content2 CLOB ,
content3 CLOB ,
image1 VARCHAR(128),
video1 VARCHAR(128),
created TIMESTAMP WITH TIME ZONE 
);

