CREATE TABLE IF NOT EXISTS users (
id INT AUTO_INCREMENT PRIMARY KEY,
fullname VARCHAR(64) NOT NULL,
email VARCHAR(64) NOT NULL,
UNIQUE KEY UK_email (email),
password VARCHAR(64) NOT NULL,
activation VARCHAR(64) NOT NULL,
enabled VARCHAR(64) NOT NULL ,
authority VARCHAR(64) NOT NULL 
);

